version: "3.8"
services:
  elasticsearch:
    image: elasticsearch:7.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.12.0
    container_name: kibana
    restart: always
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  
  app:
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - elasticsearch
      - kibana

volumes:
  elasticdata:
    driver: local